#pragma once

#include <Arduino.h>

#define CODEXMETER_DEVICE_NAME "CodexMeter"

#define CODEXMETER_SCREEN_W 480
#define CODEXMETER_SCREEN_H 480

// Waveshare ESP32-S3-Touch-AMOLED-2.16 QSPI AMOLED defaults. Keep all board
// pins here so hardware revisions can be adjusted without touching UI logic.
#define CODEXMETER_LCD_CS 12
#define CODEXMETER_LCD_SCLK 38
#define CODEXMETER_LCD_D0 4
#define CODEXMETER_LCD_D1 5
#define CODEXMETER_LCD_D2 6
#define CODEXMETER_LCD_D3 7
#define CODEXMETER_LCD_RST 2

#define CODEXMETER_I2C_SDA 15
#define CODEXMETER_I2C_SCL 14
#define CODEXMETER_AXP2101_ADDR 0x34

// Waveshare ESP32-S3-Touch-AMOLED-2.16 has three side buttons:
// left GPIO0, middle AXP2101 PKEY, right GPIO18.
#define CODEXMETER_BUTTON_LEFT_PIN 0
#define CODEXMETER_BUTTON_RIGHT_PIN 18

#define CODEXMETER_STALE_AFTER_MS (180UL * 1000UL)
#define CODEXMETER_AUTO_SCREEN_AFTER_MS (5UL * 60UL * 1000UL)
#define CODEXMETER_ALERT_HOLD_MS 8000UL
#define CODEXMETER_FLASH_STEP_MS 180UL
#define CODEXMETER_FLASH_STEPS 6
#define CODEXMETER_ALERT_REVEAL_DELAY_MS 90UL
#define CODEXMETER_ALERT_TITLE_VISUAL_OFFSET_X (-10)
#define CODEXMETER_ALERT_BODY_VISUAL_OFFSET_X (-15)
#define CODEXMETER_ALERT_DIAGNOSTICS 0
#define CODEXMETER_LVGL_SLOW_FRAME_MS 50UL
#define CODEXMETER_TTF_FONT_PATH "S:/fonts/DroidSansFallback.ttf"
#define CODEXMETER_TTF_ALERT_SIZE 28
#define CODEXMETER_TTF_TITLE_SIZE 30
#define CODEXMETER_TTF_TOKEN_SIZE 56
#define CODEXMETER_TTF_CACHE_GLYPHS 96
#define CODEXMETER_TTF_TOKEN_CACHE_GLYPHS 24
#define CODEXMETER_LVGL_PSRAM_POOL_BYTES (512UL * 1024UL)

#define CODEXMETER_BRIGHTNESS_DEFAULT 60
#define CODEXMETER_BRIGHTNESS_MIN 10
#define CODEXMETER_BRIGHTNESS_MAX 100
#define CODEXMETER_BRIGHTNESS_STEP 10
#define CODEXMETER_BRIGHTNESS_OVERLAY_MS 3000UL

#define CODEXMETER_VOLUME_DEFAULT 50
#define CODEXMETER_SETTINGS_WRITE_DELAY_MS 2000UL
#define CODEXMETER_SETTINGS_IDLE_TIMEOUT_MS 30000UL

#define CODEXMETER_THEME_AUTO_DEFAULT_MINUTES 10
#define CODEXMETER_THEME_AUTO_MIN_MINUTES 1
#define CODEXMETER_THEME_AUTO_MAX_MINUTES 1440
#define CODEXMETER_THEME_TOAST_MS 1200UL

#define CODEXMETER_BURN_IN_DRIFT_INTERVAL_MS (10UL * 60UL * 1000UL)
#define CODEXMETER_BURN_IN_DRIFT_MAX_PX 2

#define CODEXMETER_ROTATION_RAMP_STEP_MS 25UL
