[env:waveshare_amoled_216]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DXPOWERS_CHIP_AXP2101
  -DLV_CONF_SKIP
  -DLV_COLOR_DEPTH=16
  -DLV_USE_LOG=0
  -DLV_USE_LABEL=1
  -DLV_USE_OBJ=1
  -DLV_USE_BAR=1
  -DLV_USE_BTN=1
  -DLV_USE_IMAGE=1
  -DLV_USE_SNAPSHOT=1
  -DLV_TICK_CUSTOM=1
  -DLV_FONT_MONTSERRAT_16=1
  -DLV_FONT_MONTSERRAT_24=1
  -DLV_FONT_MONTSERRAT_32=1
  -DLV_FONT_MONTSERRAT_48=1
lib_deps =
  moononournation/GFX Library for Arduino@^1.6.4
  lewisxhe/XPowersLib@^0.2.7
  lvgl/lvgl@^9.2.0
  bblanchon/ArduinoJson@^7.0.0
  h2zero/NimBLE-Arduino@^2.1.1
