[env:waveshare_amoled_216]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions_16mb_tinyttf.csv
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DXPOWERS_CHIP_AXP2101
  -DLV_CONF_SKIP
  -DLV_COLOR_DEPTH=16
  -DLV_USE_LOG=0
  -DLV_USE_LABEL=1
  -DLV_USE_OBJ=1
  -DLV_USE_BAR=1
  -DLV_USE_BTN=1
  -DLV_USE_IMAGE=1
  -DLV_USE_SNAPSHOT=1
  -DLV_TICK_CUSTOM=1
  -DLV_MEM_POOL_EXPAND_SIZE=524288U
  -DLV_USE_TINY_TTF=1
  -DLV_TINY_TTF_FILE_SUPPORT=1
  -DLV_TINY_TTF_CACHE_GLYPH_CNT=96
  -DLV_TINY_TTF_CACHE_KERNING_CNT=128
  -DLV_USE_FS_ARDUINO_ESP_LITTLEFS=1
  -DLV_FS_ARDUINO_ESP_LITTLEFS_LETTER=83
  -DLV_FONT_MONTSERRAT_16=1
  -DLV_FONT_MONTSERRAT_24=1
  -DLV_FONT_MONTSERRAT_32=1
  -DLV_FONT_MONTSERRAT_48=1
lib_deps =
  moononournation/GFX Library for Arduino@1.6.6
  lewisxhe/SensorLib@0.2.6
  lewisxhe/XPowersLib@0.2.9
  lvgl/lvgl@9.5.0
  bblanchon/ArduinoJson@7.4.3
  h2zero/NimBLE-Arduino@2.5.0
